export const NEW_TOKEN = 'NEW_TOKEN'
export const TOKEN_ERROR = 'TOKEN_ERROR'
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS'

export const NEW_USER = 'NEW_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const ADD_USER = 'ADD_USER'
export const USERS_LOADING = 'USERS_LOADING'
export const USERS_ERROR = 'USERS_ERROR'
export const USERS_LOADED = 'USERS_LOADED'

export const NEW_CHANNEL = 'NEW_CHANNEL'
export const CHANNEL_ERROR = 'CHANNEL_ERROR'
export const CHANNEL_SUCCESS = 'CHANNEL_SUCCESS'

export const SET_CHANNEL = 'SET_CHANNEL'

export const ADD_CHANNEL = 'ADD_CHANNEL'
export const CHANNELS_LOADING = 'CHANNELS_LOADING'
export const CHANNELS_ERROR = 'CHANNELS_ERROR'
export const CHANNELS_LOADED = 'CHANNELS_LOADED'

export const SET_MEMBER = 'SET_MEMBER'
export const JOINED_ERROR = 'JOINED_ERROR'

export const NEW_MEMBER = 'NEW_MEMBER'
export const MEMBER_ERROR = 'MEMBER_ERROR'
export const MEMBER_SUCCESS = 'MEMBER_SUCCESS'

export const ADD_MEMBER = 'ADD_MEMBER'
export const MEMBERS_ERROR = 'MEMBERS_ERROR'
export const MEMBERS_LOADING = 'MEMBERS_LOADING'
export const MEMBERS_LOADED = 'MEMBERS_LOADED'

export const NEW_MESSAGE = 'NEW_MESSAGE'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGES_LOADING = 'MESSAGES_LOADING'
export const MESSAGES_ERROR = 'MESSAGES_ERROR'
export const MESSAGES_LOADED = 'MESSAGES_LOADED'
